export enum FontFamily {
    NotoSans_Regular = "NotoSans",
    NotoSans_Bold = "NotoSans-Bold",
    Teko_Bold = "Teko-Bold",
    Teko_Light = "Teko-Light",
    Teko_Medium = "Teko-Medium",
    Teko_Regular = "Teko-Regular",
    Teko_SemiBold = "Teko-SemiBold",
    OpenSans_Bold = "OpenSans-Bold",
    OpenSans_BoldItalic = "OpenSans-BoldItalic",
    OpenSans_ExtraBold = "OpenSans-ExtraBold",
    OpenSans_ExtraBoldItalic = "OpenSans-ExtraBoldItalic",
    OpenSans_Italic = "OpenSans-Italic",
    OpenSans_Light = "OpenSans-Light",
    OpenSans_LightItalic = "OpenSans-LightItalic",
    OpenSans_Regular = "OpenSans-Regular",
    OpenSans_SemiBold = "OpenSans-SemiBold",
    OpenSans_SemiBoldItalic = "OpenSans-SemiBoldItalic",
    Roboto_Bold = "Roboto-Bold",
    Roboto_Light = "Roboto-Light",
    Roboto_Medium = "Roboto-Medium",
    Roboto_Regular = "Roboto-Regular"
}
